### PR TITLE
Remove intent

### PR DESCRIPTION
**Pull request by JingjingShii**

### CODE REVIEW

**Comment by gjwgit** [comment]
- [x] RECOGNISE fails when location is australiaeast. Works for westus. Revert to allow any location.
- [x] RECOGNISE should catch KeyError: 'profileId' in above and suggest service not supported at that location to avoid user unfriendly error messages.
- [x] RECOGNISE catch FileNotFoundError (--file and --verify) to avoid user unfriendly error messages.
- [x] RECOGNISE output as a single line: `0.8664135336875916,accept` to facilitate pipeline usage.

**Comment by JingjingShii** [comment]
RECOGNISE only works for westus. If the user wants to run the demo, the location should be westus when they create the speech resource. 
I have added this condition in README. I'll add it in DEMO as well.

**Comment by gjwgit** [comment]
- [x] Does MLHUB.yaml still need     

```
- https://mlhub.ai/empty.txt: private_luis.txt
```

- [ ] In the demo, and with the recognise command, check location and if not "westus" then do not run the recognise demo but comment that RECOGNISE only works for westus, and for the RECOGNISE command return nothing on stdout and a message on stderr to the same effect.

Note the "westus" limitation is reported here:

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speaker-recognition?tabs=script&pivots=programming-language-curl

**Review by gjwgit — APPROVED** [review]
Do not delete private.txt but add message to edit it.

**Pull request merged**
